### ISSUE TITLE
alternate github icon

### ISSUE THREAD

**Issue by aeosynth** [jxnblk/geomicons-open#58]
hi, not sure if you're still working on this, but i'd like to request the 'standard' github icon: https://octicons.github.com/icon/mark-github/. geomicon's icon is the 'octoface': https://octicons.github.com/icon/octoface/.

**Comment by jxnblk** [comment]
I'm actually planning on removing any social media logos from this repo. I'd recommend this repo for things like GitHub: https://github.com/danleech/simple-icons
