### ISSUE TITLE
Download not working on website - please help!

### ISSUE THREAD

**Issue by robsd** [jxnblk/geomicons-open#60]
The download button on the geomicons.com website returns the error 'Not Found'.

![screenshot 2015-12-24 16 13 34](https://cloud.githubusercontent.com/assets/8268467/11996378/619d75fa-aa59-11e5-8255-dad1ef3bb8bf.png)

I really need these icons - please help someone :+1:

**Comment by kepi** [comment]
Confirmed, link on website doesn't work.

As workaround, you can download icons here on github: https://github.com/jxnblk/geomicons-open/archive/master.zip
